{% set name = "mkdocs-ivory" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://github.com/daizutabi/mkdocs-ivory/archive/v{{ version }}.tar.gz
  sha256: 99c52fa3d26862dfab9cadd616d7aec7126ff5b02c7652d955055d6777bdecb8
  # sha256: d76a2c0dccecd042c28954e7a2a5bf963496f523a028437903bd7bd70a1afe60

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3
    - pip
    - setuptools
  run:
    - mkdocs >=1
    - python >3

test:
  imports:
    - mkdocs_ivory

about:
  home: https://github.com/daizutabi/mkdocs-ivory
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ivory theme for MkDocs
  doc_url: https://github.com/daizutabi/mkdocs-ivory
  dev_url: https://github.com/daizutabi/mkdocs-ivory

extra:
  recipe-maintainers:
    - daizutabi
    - pkestene
